/*

 LEVEL_SELECT_ARROWS_TILEMAP.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 4 x 4
   Tile set      : Z:\home\platinum95\code\gb\L2D\Art\level_select_tiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level_select_arrows_tilemapWidth 4
#define level_select_arrows_tilemapHeight 4
#define level_select_arrows_tilemapBank 0

#define level_select_arrows_tilemap level_select_arrows_tilemapPLN0
unsigned char level_select_arrows_tilemapPLN0[] =
{
  0x00,0x01,0x01,0x00,0x01,0x02,0x02,0x01,0x01,0x02,
  0x02,0x01,0x00,0x01,0x01,0x00
};

unsigned char level_select_arrows_tilemapPLN1[] =
{
  0x00,0x00,0x20,0x00,0x00,0x00,0x00,0x20,0x40,0x00,
  0x00,0x60,0x00,0x40,0x60,0x00
};

/* End of LEVEL_SELECT_ARROWS_TILEMAP.C */
