/*

 PIPES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 13

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define PipeTilesBank 0

/* Gameboy Color palette 0 */
#define PipeTilesCGBPal0c0 26425
#define PipeTilesCGBPal0c1 672
#define PipeTilesCGBPal0c2 2896
#define PipeTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define PipeTilesCGBPal1c0 6076
#define PipeTilesCGBPal1c1 8935
#define PipeTilesCGBPal1c2 6596
#define PipeTilesCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define PipeTilesCGBPal2c0 6076
#define PipeTilesCGBPal2c1 8935
#define PipeTilesCGBPal2c2 6596
#define PipeTilesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define PipeTilesCGBPal3c0 6076
#define PipeTilesCGBPal3c1 8935
#define PipeTilesCGBPal3c2 6596
#define PipeTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define PipeTilesCGBPal4c0 6076
#define PipeTilesCGBPal4c1 8935
#define PipeTilesCGBPal4c2 6596
#define PipeTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define PipeTilesCGBPal5c0 6076
#define PipeTilesCGBPal5c1 8935
#define PipeTilesCGBPal5c2 6596
#define PipeTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define PipeTilesCGBPal6c0 6076
#define PipeTilesCGBPal6c1 8935
#define PipeTilesCGBPal6c2 6596
#define PipeTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define PipeTilesCGBPal7c0 6076
#define PipeTilesCGBPal7c1 8935
#define PipeTilesCGBPal7c2 6596
#define PipeTilesCGBPal7c3 5344

/* CGB palette entries. */
#define PipeTilesCGB0 0
#define PipeTilesCGB1 0
#define PipeTilesCGB2 0
#define PipeTilesCGB3 0
#define PipeTilesCGB4 0
#define PipeTilesCGB5 0
#define PipeTilesCGB6 0
#define PipeTilesCGB7 0
#define PipeTilesCGB8 0
#define PipeTilesCGB9 0
#define PipeTilesCGB10 0
#define PipeTilesCGB11 0
#define PipeTilesCGB12 0
#define PipeTilesCGB13 0
/* Start of tile array. */
extern unsigned char PipeTiles[];

/* End of PIPES.H */
