/*

 PIPES_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 10
   Tile set      : Z:\home\platinum95\code\gb\BlappyFirds\pipes.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define PipesTilemapWidth 10
#define PipesTilemapHeight 10
#define PipesTilemapBank 0

extern unsigned char PipesTilemap[];

/* End of PIPES_MAP.H */
