/*

 SPLASH_TILEMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 18
   Tile set      : Z:\home\platinum95\code\gb\L2D\Art\SpashTiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splash_tilemapWidth 32
#define splash_tilemapHeight 18
#define splash_tilemapBank 0

#define splash_tilemap splash_tilemapPLN0
extern unsigned char splash_tilemapPLN0[];
extern unsigned char splash_tilemapPLN1[];

/* End of SPLASH_TILEMAP.H */
