/*

 EXPORT.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 10

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SplashTilesBank 0

/* Super Gameboy palette 0 */
#define SplashTilesSGBPal0c0 6076
#define SplashTilesSGBPal0c1 8935
#define SplashTilesSGBPal0c2 6596
#define SplashTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SplashTilesSGBPal1c0 6076
#define SplashTilesSGBPal1c1 8935
#define SplashTilesSGBPal1c2 6596
#define SplashTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SplashTilesSGBPal2c0 6076
#define SplashTilesSGBPal2c1 8935
#define SplashTilesSGBPal2c2 6596
#define SplashTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SplashTilesSGBPal3c0 6076
#define SplashTilesSGBPal3c1 8935
#define SplashTilesSGBPal3c2 6596
#define SplashTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SplashTilesCGBPal0c0 32767
#define SplashTilesCGBPal0c1 26425
#define SplashTilesCGBPal0c2 15855
#define SplashTilesCGBPal0c3 0

/* Gameboy Color palette 1 */
#define SplashTilesCGBPal1c0 11145
#define SplashTilesCGBPal1c1 14983
#define SplashTilesCGBPal1c2 2142
#define SplashTilesCGBPal1c3 1022

/* Gameboy Color palette 2 */
#define SplashTilesCGBPal2c0 11145
#define SplashTilesCGBPal2c1 14983
#define SplashTilesCGBPal2c2 1022
#define SplashTilesCGBPal2c3 2142

/* Gameboy Color palette 3 */
#define SplashTilesCGBPal3c0 7602
#define SplashTilesCGBPal3c1 32767
#define SplashTilesCGBPal3c2 6596
#define SplashTilesCGBPal3c3 0

/* Gameboy Color palette 4 */
#define SplashTilesCGBPal4c0 32767
#define SplashTilesCGBPal4c1 32650
#define SplashTilesCGBPal4c2 14983
#define SplashTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SplashTilesCGBPal5c0 32767
#define SplashTilesCGBPal5c1 14983
#define SplashTilesCGBPal5c2 14983
#define SplashTilesCGBPal5c3 0

/* Gameboy Color palette 6 */
#define SplashTilesCGBPal6c0 32767
#define SplashTilesCGBPal6c1 32650
#define SplashTilesCGBPal6c2 32767
#define SplashTilesCGBPal6c3 0

/* Gameboy Color palette 7 */
#define SplashTilesCGBPal7c0 6076
#define SplashTilesCGBPal7c1 8935
#define SplashTilesCGBPal7c2 6596
#define SplashTilesCGBPal7c3 5344
/* Start of tile array. */
#define SplashTilesLen 11
#define SplashPalettesLen 8
extern unsigned char SplashTiles[];
extern unsigned short SplashPalettes[];

/* End of EXPORT.H */
