/*

 SPLASH_SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : Tile-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 15

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define splash_spritesBank 0

/* Super Gameboy palette 0 */
#define splash_spritesSGBPal0c0 6076
#define splash_spritesSGBPal0c1 8935
#define splash_spritesSGBPal0c2 6596
#define splash_spritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define splash_spritesSGBPal1c0 6076
#define splash_spritesSGBPal1c1 8935
#define splash_spritesSGBPal1c2 6596
#define splash_spritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define splash_spritesSGBPal2c0 6076
#define splash_spritesSGBPal2c1 8935
#define splash_spritesSGBPal2c2 6596
#define splash_spritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define splash_spritesSGBPal3c0 6076
#define splash_spritesSGBPal3c1 8935
#define splash_spritesSGBPal3c2 6596
#define splash_spritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define splash_spritesCGBPal0c0 32767
#define splash_spritesCGBPal0c1 1022
#define splash_spritesCGBPal0c2 21311
#define splash_spritesCGBPal0c3 5120

/* Gameboy Color palette 1 */
#define splash_spritesCGBPal1c0 32767
#define splash_spritesCGBPal1c1 31530
#define splash_spritesCGBPal1c2 5308
#define splash_spritesCGBPal1c3 0

/* Gameboy Color palette 2 */
#define splash_spritesCGBPal2c0 6076
#define splash_spritesCGBPal2c1 8935
#define splash_spritesCGBPal2c2 6596
#define splash_spritesCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define splash_spritesCGBPal3c0 6076
#define splash_spritesCGBPal3c1 8935
#define splash_spritesCGBPal3c2 6596
#define splash_spritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define splash_spritesCGBPal4c0 6076
#define splash_spritesCGBPal4c1 8935
#define splash_spritesCGBPal4c2 6596
#define splash_spritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define splash_spritesCGBPal5c0 6076
#define splash_spritesCGBPal5c1 8935
#define splash_spritesCGBPal5c2 6596
#define splash_spritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define splash_spritesCGBPal6c0 6076
#define splash_spritesCGBPal6c1 8935
#define splash_spritesCGBPal6c2 6596
#define splash_spritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define splash_spritesCGBPal7c0 6076
#define splash_spritesCGBPal7c1 8935
#define splash_spritesCGBPal7c2 6596
#define splash_spritesCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char splash_sprites[];
#define splash_spritesLen 16

/* End of SPLASH_SPRITES.H */
