/*

 SPLASH_TITLE_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 13 x 7
   Tile set      : Z:\home\platinum95\code\gb\L2D\Art\SplashWindow.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define splash_title_mapWidth 13
#define splash_title_mapHeight 7
#define splash_title_mapBank 0

#define splash_title_map splash_title_mapPLN0
extern unsigned char splash_title_mapPLN0[];
extern unsigned char splash_title_mapPLN1[];

/* End of SPLASH_TITLE_MAP.H */
