/*

 TILE_DATA.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 17

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : Constant per entry.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define TileDataBank 0

/* Gameboy Color palette 0 */
#define TileDataCGBPal0c0 26425
#define TileDataCGBPal0c1 672
#define TileDataCGBPal0c2 2896
#define TileDataCGBPal0c3 0

/* Gameboy Color palette 1 */
#define TileDataCGBPal1c0 32767
#define TileDataCGBPal1c1 6111
#define TileDataCGBPal1c2 5918
#define TileDataCGBPal1c3 5285

/* Gameboy Color palette 2 */
#define TileDataCGBPal2c0 32767
#define TileDataCGBPal2c1 5918
#define TileDataCGBPal2c2 4255
#define TileDataCGBPal2c3 5285

/* CGB palette entries. */
#define TileDataCGB0 0
#define TileDataCGB1 0
#define TileDataCGB2 0
#define TileDataCGB3 0
#define TileDataCGB4 0
#define TileDataCGB5 0
#define TileDataCGB6 0
#define TileDataCGB7 0
#define TileDataCGB8 0
#define TileDataCGB9 0
#define TileDataCGB10 0
#define TileDataCGB11 0
#define TileDataCGB12 0
#define TileDataCGB13 1
#define TileDataCGB14 1
#define TileDataCGB15 1
#define TileDataCGB16 2
#define TileDataCGB17 0
/* Start of tile array. */
extern unsigned char TileData[];

/* End of TILE_DATA.H */
